version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: momento
      POSTGRES_USER: momento_user
      POSTGRES_PASSWORD: momento_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://momento_user:momento_password@db:5432/momento
      SECRET_KEY: your-secret-key-here-change-this-in-production
      OPENAI_API_KEY: your-openai-api-key-here
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: